### ISSUE TITLE
Error when closing windows with alpha opened

### ISSUE THREAD

**Issue by Bekaboo** [goolord/alpha-nvim#168]
please *read the documentation* before asking questions about configuration or creating a feature request

for bugs: provide the expected behavior and the actual behavior, and screenshots if you want to be nice

Minimal config:

```lua
local alpha = require('alpha')
local dashboard = require('alpha.themes.dashboard')
alpha.setup(dashboard.opts)
```

To reproduce this issue:

1. Install alpha with default config
2. Open nvim by `nvim`
3. Split window with `<C-w>s` or `<C-w>v`
4. Close window with `<C-w>o`

Demo:

https://user-images.githubusercontent.com/76579810/211458731-e4dce6b4-9dbf-4ca5-a0ad-5ab573d5db25.mp4

**Comment by bew** [comment]
Hello, I'm getting the same error but with another workflow (but not the one you described):

1. Install alpha with default config
2. Open nvim by nvim
3. Split window with <C-w>s or <C-w>v
4. Open one of the recent file in the alpha buffer (only in one window, alpha is still visible in the other window)
5. Close the window with the opened file (using `:q` for example)

And I get the error:
```
Error detected while processing CursorMoved Autocommands for "<buffer=1>":
Error executing lua callback: ...pack/lazy-managed-plugins/start/alpha-nvim/lua/alpha.lua:567: Invalid window id: 1000
stack traceback:
        [C]: in function 'nvim_win_get_cursor'
        ...pack/lazy-managed-plugins/start/alpha-nvim/lua/alpha.lua:567: in function 'move_cursor'
        ...pack/lazy-managed-plugins/start/alpha-nvim/lua/alpha.lua:473: in function <...pack/lazy-managed-plugins/start/alpha-nvim/lua/alpha.lua:473>
```

---
NOTE: Writing this comment, I noticed another bug: splitting the Alpha window actually doesn't work, the new window doesn't have the same bindings as the first window..

**Comment by goolord** [comment]
should be fixed in 704ff0fc0660caf85080f1443ccf6e03ea401fe6

**Comment by Bekaboo** [comment]
@goolord Hi, this is actually not fixed, and here is a demo of the bug:


https://user-images.githubusercontent.com/76579810/235388519-fc109330-0a75-49fe-90f6-01dc7b999cae.mp4

**Comment by goolord** [comment]
probably reintroduced by https://github.com/goolord/alpha-nvim/pull/201

**Comment by goolord** [comment]
reverted, confirmed it's fixed @Bekaboo 

maybe i should get to writing tests for this plugin now, which i'm not totally sure how i'll do

**Comment by Bekaboo** [comment]
@goolord I tested it again and seems that it is only fixed for the `startify` theme but not for `dashboard` and `theta`. I'm testing against the default config, i.e. `requirerequire'alpha'.setup(require'alpha.themes.theta'.config)` and `require('alpha').setup(require('alpha.themes.dashboard').config)`.

**Comment by goolord** [comment]
ok, i have made window handling a bit more principled, and this should be fixed in the `theta` and `dashboard` themes
